#!/usr/bin/env python3
"""Claude hook adapter: attest caller identity and gate registered native calls.

The plugin runs this script for spawns, advisor hand-backs, routing MCP calls
and subagent lifecycle events. Definitions generated by earlier releases also
call it from their frontmatter with `--scope agent`; that scope answers nothing
now, because the host's own tool allowlist confines the advisor. Without an
explicit required-mode configuration it returns no decision at all.
"""
from __future__ import annotations

import copy
import json
import re
import math
import os
from pathlib import Path
import secrets
import sys
import time

# `python -I` intentionally ignores the working directory and PYTHONPATH. Import
# only this installed script's sibling package, not files from the user's cwd.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from route_evidence.claude_agents import CLAUDE_MODEL_ALIASES, check_record, observe_alias, resolve_variant, unrouted_model
from route_evidence.core import EvidenceError, digest
from route_evidence.pipeline import RECEIPT_SECONDS, arguments
from route_evidence.pipeline_config import ADVISOR_TOOLS, ROOT_TOOLS, ROUTING_TOOLS, settings, runtime_overrides
from route_evidence.pipeline_store import PipelineStore
from route_evidence.service import load_config

MAX_INPUT = 8 * 1024 * 1024
SPAWN_TOOLS = {"Agent", "Task"}
HANDBACK = "SubagentHandback"
DAY = 86400
# Fields that describe what the host actually ran, as opposed to what was
# authorized. They move with an agent when its attribution is corrected.
RUNTIME_FIELDS = ("agent_id", "state", "observed_model", "observed_effort", "efforts_used", "models_used", "binding")


def output(event, **fields):
    return {"hookSpecificOutput": {"hookEventName": event, **fields}}


def deny(reason):
    return output("PreToolUse", permissionDecision="deny", permissionDecisionReason="Assay: " + reason)


def routing_operation(tool, server=None):
    """The routing MCP operation a tool name addresses, if any."""
    if not isinstance(tool, str) or not tool.startswith("mcp__"):
        return None
    prefix, _, name = tool.rpartition("__")
    if name not in ROUTING_TOOLS or (server is not None and prefix != "mcp__" + server):
        return None
    return name


def guarded(event):
    """Operations that must be refused when the guard cannot validate them."""
    return event.get("hook_event_name") == "PreToolUse" and (
        event.get("tool_name") in SPAWN_TOOLS | {HANDBACK} or routing_operation(event.get("tool_name")) is not None)


def _identity(event):
    session = event.get("session_id")
    agent = event.get("agent_id")
    if not isinstance(session, str) or not session or len(session) > 200:
        raise EvidenceError("host_session_identity_missing")
    if agent is not None and (not isinstance(agent, str) or not agent or len(agent) > 200):
        raise EvidenceError("host_agent_identity_invalid")
    return session, agent


def observe_effort(run, event):
    raw = event.get("effort")
    if raw is None:
        return
    level = raw.get("level") if isinstance(raw, dict) else None
    if not isinstance(level, str) or level not in {"low", "medium", "high", "xhigh", "max"}:
        raise EvidenceError("invalid_observed_effort_object")
    run["efforts_used"] = sorted(set(run.get("efforts_used", [])) | {level})
    run["observed_effort"] = level
    if run.get("binding") != "start_order" and level != run["route"]["effort"]:
        run["route_mismatch"] = True


def _unrouted(event, mode):
    """The owner's entry for a root launch of an exempt native agent type, if any."""
    supplied = event.get("tool_input")
    if event.get("agent_id") is not None or not isinstance(supplied, dict):
        return None
    return mode["unrouted_agents"].get(supplied.get("subagent_type") or "general-purpose")


def _unrouted_launch(event, mode, spec, environment=None):
    """Launch an exempt type with its configured model instead of the parent's.

    Only the model changes; every other field, including run_in_background,
    stays the caller's. A different model from the root is an explicit choice
    and goes through prepare_routing like any other.
    """
    try:
        model = unrouted_model(mode, spec)
    except EvidenceError as exc:
        return deny(f"exempt agent type has no model the Agent call accepts ({exc}); run the routing doctor")
    if model is not None:
        overrides = runtime_overrides({"model": model, "effort": "low"}, environment, host=mode.get("host"))
        if "model_environment_override" in overrides["conflicts"] or "forced_model_unresolved" in overrides["unverified"]:
            return deny("exempt agent model conflicts with the client's environment precedence; run the routing doctor")
    supplied = event["tool_input"]
    if model is None or supplied.get("model") == model:
        return {}
    if supplied.get("model") is not None:
        return deny("exempt agent types launch with their configured model; route another model through prepare_routing")
    return output("PreToolUse", updatedInput={**supplied, "model": model})


def _observe_unrouted(tx, event, clock):
    """An exempt launch still reports what its alias resolved to."""
    supplied, response = event.get("tool_input"), event.get("tool_response")
    alias = supplied.get("model") if isinstance(supplied, dict) else None
    model = response.get("resolvedModel") if isinstance(response, dict) else None
    if event.get("agent_id") is None and alias in CLAUDE_MODEL_ALIASES and isinstance(model, str) and model:
        observe_alias(tx, alias, model, clock())


def _save(tx, session, run, clock):
    tx.put("attempt", run["attempt_id"], run, clock() + DAY)
    if run.get("agent_id"):
        tx.put("agent", session + ":" + run["agent_id"], run, clock() + DAY)


def _bind_start(tx, session, config_hash, agent, agent_type, clock):
    if not agent:
        return
    candidates = [r for r in tx.values("attempt") if r["session_id"] == session
                  and r["config_hash"] == config_hash and r["state"] == "reserved" and not r.get("agent_id")
                  and r["variant"]["name"] == agent_type and clock() < r["expires"]]
    if not candidates:
        return
    # SubagentStart carries no parent tool-use ID. Launches of one definition
    # can share effort/permissions but NOT the per-call model. Reservation order
    # is provisional only; do not validate the route against this attribution.
    # A last remaining reservation is still ambiguous when an earlier start
    # could belong to it. The result naming both IDs resolves attribution.
    ambiguous = len(candidates) > 1 or any(
        r["session_id"] == session and r["config_hash"] == config_hash
        and r["variant"]["name"] == agent_type and r.get("binding") == "start_order"
        for r in tx.values("attempt"))
    run = min(candidates, key=lambda r: (r.get("reserved_at", 0), r["attempt_id"]))
    run.update(state="started", agent_id=agent, binding="start_order" if ambiguous else "unique")
    run.pop("input", None)
    _save(tx, session, run, clock)


def _swap_runtime(first, second):
    for key in RUNTIME_FIELDS:
        a, b = first.get(key), second.get(key)
        a_present, b_present = key in first, key in second
        first.pop(key, None)
        second.pop(key, None)
        if b_present:
            first[key] = b
        if a_present:
            second[key] = a


def _rebind(tx, session, dispatched, observed_id, clock):
    """Attribute the agent the host names to the call that actually started it."""
    other = tx.get("agent", session + ":" + observed_id)
    if other and other["attempt_id"] != dispatched["attempt_id"]:
        sibling = tx.get("attempt", other["attempt_id"])
        if sibling and (sibling["variant"]["name"] != dispatched["variant"]["name"] or sibling.get("binding") == "host_result"):
            raise EvidenceError("host_agent_binding_conflict")
        if sibling and sibling["variant"]["name"] == dispatched["variant"]["name"]:
            # Start order gave this agent to a sibling launch of the same
            # definition. Exchange what each actually ran; a sibling left
            # without an agent is still awaiting its own start event.
            _swap_runtime(dispatched, sibling)
            if "agent_id" not in sibling:
                sibling["state"] = "reserved"
            _recheck_observed(sibling)
            _save(tx, session, sibling, clock)
    if dispatched.get("agent_id") != observed_id:
        dispatched["agent_id"] = observed_id
    if dispatched["state"] in {"prepared", "reserved"}:
        dispatched["state"] = "started"
    dispatched["binding"] = "host_result"
    _recheck_observed(dispatched)
    return dispatched


def _recheck_observed(run):
    """Mismatch is derived from evidence and the final route, never swapped."""
    run.pop("route_mismatch", None)
    if run.get("binding") == "start_order":
        return
    level = run.get("observed_effort")
    expected = run["route"]["model"]
    model = run.get("observed_model")
    used = run.get("models_used", [])
    levels = run.get("efforts_used", [level] if level else [])
    if (any(value != run["route"]["effort"] for value in levels)
            or (expected not in CLAUDE_MODEL_ALIASES and
                ((model is not None and model != expected) or any(m != expected for m in used)))
            or (expected in CLAUDE_MODEL_ALIASES and model and any(m != model for m in used))):
        run["route_mismatch"] = True


def _observe_model(tx, run, response, clock):
    """Compare what the host ran with the route.

    A pinned ID must match exactly. A rolling alias is checked through its
    recorded resolution: a new resolution is an inventory event, while a model
    switch inside one run is still a mismatch.
    """
    expected = run["route"]["model"]
    model = response.get("resolvedModel")
    used = response.get("modelsUsed")
    used = [m for m in used if isinstance(m, str) and m] if isinstance(used, list) else []
    previous_model = run.get("observed_model")
    used = list(dict.fromkeys([*run.get("models_used", []), *([previous_model] if previous_model else []), *used,
                              *([model] if isinstance(model, str) and model else [])]))
    if len(used) > 64 or any(len(item) > 200 for item in used):
        raise EvidenceError("observed_model_history_exceeds_bound")
    if isinstance(model, str) and model:
        run["observed_model"] = model
    run["models_used"] = used
    if run.get("binding") == "start_order":
        return
    if expected not in CLAUDE_MODEL_ALIASES:
        if run.get("observed_model") not in (None, expected) or any(m != expected for m in used):
            run["route_mismatch"] = True
        return
    # The host reports the full ID an alias resolved to, never the alias itself.
    resolved = run.get("observed_model") or (used[0] if len(set(used)) == 1 else None)
    if resolved is None:
        return
    change = observe_alias(tx, expected, resolved, clock())
    if change:
        run["alias_changed"] = {"from": change["from"], "to": change["to"]}
    if any(m != resolved for m in used):
        run["route_mismatch"] = True


def _observe_return(tx, event, session, config_hash, name, clock):
    tool = event.get("tool_name")
    matches = [r for r in tx.values("attempt") if r.get("tool_use_id") == event.get("tool_use_id")
               and r["session_id"] == session and r["config_hash"] == config_hash]
    if len(matches) != 1:
        if name == "PostToolUse":
            _observe_unrouted(tx, event, clock)
        return {}
    dispatched = matches[0]
    response = event.get("tool_response")
    observed_id = response.get("agentId", response.get("agent_id")) if isinstance(response, dict) else None
    if isinstance(observed_id, str) and observed_id:
        dispatched = _rebind(tx, session, dispatched, observed_id, clock)
    dispatched["host_returned"] = True
    dispatched.pop("input", None)
    if name == "PostToolUseFailure":
        dispatched["state"] = "failed"
    else:
        # Native result layouts can vary. Do not invent an agent ID or a model
        # when the host supplies no structured value.
        status = response.get("status") if isinstance(response, dict) else None
        previous_state = dispatched["state"]
        dispatched["state"] = (previous_state if status == "async_launched" and previous_state in {"finished", "failed"}
                               else "running" if status == "async_launched" else "finished"
                               if status == "completed" else previous_state)
        if isinstance(response, dict):
            _observe_model(tx, dispatched, response, clock)
    _save(tx, session, dispatched, clock)
    if dispatched["role"] == "advisor" and name == "PostToolUse" and tool in SPAWN_TOOLS:
        # Unknown output layouts must not create an unfiltered report
        # channel. Rebuild the documented text envelope; copy only numeric
        # telemetry, never arbitrary nested fields or error messages.
        safe = {"content": [{"type": "text", "text": json.dumps({
            "decision_id": dispatched["decision_id"], "status": "read_registered_decision"})}]}
        if dispatched.get("agent_id"):
            safe["agentId"] = dispatched["agent_id"]
        if isinstance(response, dict):
            if response.get("status") in {"completed", "async_launched"}:
                safe["status"] = response["status"]
            # Preserve bounded native routing telemetry, never arbitrary text
            # or nested report/error fields from an advisor.
            model_token = re.compile(r"[A-Za-z0-9][A-Za-z0-9._:/-]{0,199}\Z")
            model = response.get("resolvedModel")
            if isinstance(model, str) and model_token.fullmatch(model):
                safe["resolvedModel"] = model
            used = response.get("modelsUsed")
            if isinstance(used, list) and len(used) <= 16 and all(isinstance(v, str) and model_token.fullmatch(v) for v in used):
                safe["modelsUsed"] = used
            for key in ("totalDurationMs", "totalTokens", "totalToolUseCount"):
                if type(response.get(key)) in (int, float) and 0 <= response[key] < 10**15 and math.isfinite(response[key]):
                    safe[key] = response[key]
        return output(name, updatedToolOutput=safe)
    return {}


def _release(tx, event, session, config_hash, clock):
    """Auto mode denied a reserved launch before it ran; it may be sent again."""
    for run in tx.values("attempt"):
        if (run.get("tool_use_id") == event.get("tool_use_id") and run["session_id"] == session
                and run["config_hash"] == config_hash and run["state"] == "reserved" and not run.get("agent_id")):
            run["state"] = "prepared"
            run.pop("tool_use_id", None)
            run.pop("reserved_at", None)
            tx.put("attempt", run["attempt_id"], run, run["expires"])
    return {}


def _dispatch(tx, event, session, config_hash, mode, clock, environment):
    supplied = event["tool_input"]
    candidates = [r for r in tx.values("attempt") if r["session_id"] == session
                  and r["config_hash"] == config_hash and r["input_hash"] == digest(supplied)
                  and clock() < r["expires"] and r["state"] in {"prepared", "reserved"}]
    if len(candidates) != 1:
        return deny("no valid registered launch matches these exact arguments; call authorize_routing_launch")
    dispatched = candidates[0]
    if dispatched["role"] == "advisor" and any(
            r["attempt_id"] != dispatched["attempt_id"] and r["session_id"] == session
            and r["config_hash"] == config_hash and r["variant"]["name"] == dispatched["variant"]["name"]
            and r["state"] in {"reserved", "started", "running"} and not r.get("host_returned")
            for r in tx.values("attempt")):
        return deny("another advisor with this definition awaits authoritative host binding; finish it before launching another")
    tool_id = event.get("tool_use_id")
    if not isinstance(tool_id, str) or not tool_id:
        return deny("host tool-use identity missing")
    if dispatched["state"] == "reserved" and dispatched["tool_use_id"] != tool_id:
        return deny("launch attempt already consumed")
    if "input" not in dispatched:
        return deny("launch attempt already started")
    current = resolve_variant(mode, dispatched["variant"]["profile"], dispatched["route"], environment=environment)
    if current != dispatched["variant"]:
        return deny("agent definition changed; prepare routing again")
    check_record(Path(mode["agents_dir"]), dispatched["variant"])
    resume = dispatched["input"].get("resume")
    if resume is not None:
        original = tx.get("agent", session + ":" + resume)
        if (not original or original["role"] != "worker" or original["decision_id"] != dispatched["decision_id"]
                or original["packet_id"] != dispatched["packet_id"]
                or original["attempt_id"] != dispatched.get("continuation_of")):
            return deny("continuation identity or scope changed")
        dispatched["agent_id"] = resume
    dispatched.update(state="reserved", tool_use_id=tool_id)
    dispatched.setdefault("reserved_at", clock())
    tx.put("attempt", dispatched["attempt_id"], dispatched, clock() + DAY)
    if resume is not None:
        tx.put("agent", session + ":" + resume, dispatched, clock() + DAY)
    # The registered input replaces the stub. No permission decision is added:
    # the client's ordinary permission flow evaluates the substituted input.
    return output("PreToolUse", updatedInput=copy.deepcopy(dispatched["input"]))


def handle(event: dict, config: dict, *, scope="plugin", clock=time.time, environment=None):
    if scope == "agent":
        # A definition's own guard hook from an earlier release. The host's tool
        # allowlist confines the advisor, and effort is checked after the run.
        return {}
    mode = settings(config)
    if mode["mode"] != "required" or config.get("client") != "claude":
        # Opt-in only: no configuration, evidence-only and hosts without this
        # adapter keep the client's ordinary behavior and receive no context.
        return {}
    name, tool = event.get("hook_event_name"), event.get("tool_name")
    if mode["host"]["surface"] not in {"cli", "unknown"}:
        if guarded(event):
            return deny("required routing is not qualified for this declared client surface")
        if name == "SessionStart":
            return output(name, additionalContext="Assay: required routing has no qualified adapter for this declared client surface. Protected operations are blocked; ordinary work is unaffected.")
        return {}
    if name == "PreToolUse" and tool in SPAWN_TOOLS:
        supplied = event.get("tool_input")
        if isinstance(supplied, dict) and {"effort", "model_reasoning_effort", "reasoning_effort"} & set(supplied):
            return deny("Claude Agent has no per-call effort field; use the registered generated definition")
        spec = _unrouted(event, mode)
        if spec is not None:
            return _unrouted_launch(event, mode, spec, environment)
    # A baseline is part of the setup: without it an abstaining or failed
    # advisor would leave every packet without a route.
    if not mode["state_dir"] or not mode["agents_dir"] or not mode["baseline"]:
        if name == "PreToolUse" and tool in SPAWN_TOOLS:
            return deny("required routing setup is incomplete; run the routing doctor or select evidence-only mode")
        if name == "SessionStart":
            return output(name, additionalContext="Assay required routing is selected but not set up. Delegation outside configured unrouted agents stays blocked; run the routing doctor.")
        return {}
    session, agent = _identity(event)
    config_hash = digest(config)
    store = PipelineStore(Path(mode["state_dir"]), clock=clock)
    operation = routing_operation(tool, mode["mcp_server"])
    relevant = (name in {"SessionStart", "SessionEnd", "SubagentStart", "SubagentStop", "PermissionDenied"}
                or tool in SPAWN_TOOLS or tool == HANDBACK or operation is not None)
    if not relevant:
        return {}
    with store.transaction() as tx:
        if name == "SessionStart":
            tx.put("session", session, {"session_id": session, "config_hash": config_hash}, clock() + DAY)
            return output(name, additionalContext="Assay required routing is configured. Before authorized delegation use prepare_routing, launch only its registered advisor input, then get_routing_decision and authorize_routing_launch; send the returned Agent input unchanged, including its model. Do not read or rerank benchmark snapshots in the root. Exempt agent types get their configured model; no root settings change.")
        if name == "SessionEnd":
            for kind, id_key in (("decision", "decision_id"), ("attempt", "attempt_id")):
                for record in tx.values(kind):
                    if record["session_id"] == session:
                        tx.delete(kind, record[id_key])
            for record in tx.values("agent"):
                if record["session_id"] == session:
                    tx.delete("agent", session + ":" + record["agent_id"])
            tx.db.execute("DELETE FROM records WHERE kind='receipt' AND json_extract(payload, '$.session_id')=?", (session,))
            tx.delete("session", session)
            return {}
        registered = tx.get("session", session)
        if not registered or registered["config_hash"] != config_hash:
            if name == "PreToolUse" and (tool in SPAWN_TOOLS or operation is not None):
                return deny("hook session not registered for this configuration; reconnect the client")
            return {}
        # Activity keeps a registration alive; only an idle day retires it.
        tx.put("session", session, registered, clock() + DAY)
        if name == "SubagentStart":
            # Start is observation, not permission: never pretend to block it.
            _bind_start(tx, session, config_hash, agent, event.get("agent_type"), clock)
            return {}
        run = tx.get("agent", session + ":" + agent) if agent else None
        if name == "SubagentStop":
            if run:
                observe_effort(run, event)
                run["state"] = "finished"
                _save(tx, session, run, clock)
            return {}
        if name == "PermissionDenied" and tool in SPAWN_TOOLS:
            return _release(tx, event, session, config_hash, clock)
        if name in {"PostToolUse", "PostToolUseFailure"} and tool in SPAWN_TOOLS:
            return _observe_return(tx, event, session, config_hash, name, clock)
        if name != "PreToolUse":
            return {}
        supplied = event.get("tool_input")
        if not isinstance(supplied, dict):
            return deny("invalid tool input")
        if agent and tool in SPAWN_TOOLS:
            return deny("workers and advisors must not spawn agents")
        if tool == HANDBACK:
            if run and run["role"] == "advisor":
                state = tx.get("decision", run["decision_id"])
                submitted = bool(state and state.get("completion_hash"))
                message = json.dumps({"decision_id": run["decision_id"], "status": "submitted" if submitted else "not_submitted"})
                if set(supplied) - {"message", "summary"}:
                    return deny("unknown advisor handback fields; use only the registered decision status")
                safe = {**supplied, "message": message}
                # Avoid a second free-text report channel in newer clients.
                if "summary" in safe:
                    safe["summary"] = message
                return output(name, updatedInput=safe)
            return {}
        if run:
            if run.get("route_mismatch"):
                return deny("observed model differs from the registered route")
            if run["role"] == "advisor" and operation not in ADVISOR_TOOLS:
                return deny("advisor may only fetch its own input and submit its result")
            observe_effort(run, event)
            _save(tx, session, run, clock)
            if run.get("route_mismatch"):
                return deny("observed agent effort differs from the registered route")
        if tool in SPAWN_TOOLS:
            return _dispatch(tx, event, session, config_hash, mode, clock, environment)
        if operation in ROOT_TOOLS and agent:
            return deny("root-only routing operation")
        if operation in ADVISOR_TOOLS and (not run or run.get("binding") == "start_order" or run["role"] != "advisor"
                                           or run["decision_id"] != supplied.get("decision_id")):
            return deny("advisor identity is not bound to this decision")
        token = secrets.token_urlsafe(32)
        receipt = {"session_id": session, "agent_id": agent, "config_hash": config_hash,
                   "tool": operation, "arguments_hash": digest(arguments(supplied))}
        tx.put("receipt", digest(token), receipt, clock() + RECEIPT_SECONDS)
        return output(name, updatedInput={**supplied, "host_receipt": token})


def failure(event, scope, configured):
    """Fail closed only where the guard is the gate; never stall anything else."""
    if scope == "plugin" and guarded(event):
        return deny("routing guard could not validate this operation; run the routing doctor")
    if scope == "plugin" and configured and event.get("hook_event_name") == "PostToolUse" and event.get("tool_name") in SPAWN_TOOLS:
        # On an internal error the role is not trustworthy. Redact even a worker
        # result instead of accidentally leaking an advisor's private report.
        return output("PostToolUse", updatedToolOutput={"content": [{"type": "text", "text":
            "Assay could not validate this agent return. Its contents were withheld; diagnose the routing guard before retrying."}]})
    if scope == "plugin" and configured and event.get("hook_event_name") == "SessionStart":
        return output("SessionStart", additionalContext="Assay routing configuration is invalid or unavailable. Registered delegation stays blocked until the routing doctor passes.")
    return {}


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    scope = "agent" if list(argv[:2]) == ["--scope", "agent"] else "plugin"
    raw = sys.stdin.buffer.read(MAX_INPUT + 1)
    try:
        if len(raw) > MAX_INPUT:
            raise EvidenceError("oversized_event")
        event = json.loads(raw)
        if not isinstance(event, dict):
            raise EvidenceError("invalid_event")
    except (ValueError, RecursionError):
        # A conforming host never sends an unreadable event, and its kind is
        # unknown. Only the plugin guard fails closed; payloads are not echoed.
        if scope == "plugin":
            print("Assay routing guard could not read the hook event.", file=sys.stderr)
            return 2
        print("{}")
        return 0
    path = os.environ.get("ASSAY_ROUTING_CONFIG")
    try:
        config = load_config(Path(path)) if path else {}
        result = handle(event, config, scope=scope)
    except Exception:  # noqa: BLE001 - every failure is classified by the operation it guards
        result = failure(event, scope, bool(path))
    # ASCII JSON: a substituted prompt may hold any script, and the host console
    # encoding (for example cp1251) must not decide whether it arrives intact.
    print(json.dumps(result))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
